(() => {
  'use strict';

  // ---------- 처방 카테고리 메타 ----------
  // "emotion"은 기존 SYMPTOMS(app.js)를 어댑터로 감싼 것이며, 여기엔 콘텐츠를 직접 넣지 않는다.
  // 콘텐츠가 아직 없는 카테고리(sleep/social/study/fun/random)는 처방센터에서 "곧 추가돼요"로 표시된다.
  const RX_CATEGORIES = [
    { id: 'emotion', label: '감정', emoji: '❤️', color: '#ff9166' },
    { id: 'work', label: '직장', emoji: '💼', color: '#9aa8e0' },
    { id: 'love', label: '연애', emoji: '💕', color: '#ff8fb3' },
    { id: 'money', label: '돈', emoji: '💰', color: '#ffc66b' },
    { id: 'food', label: '음식', emoji: '🍗', color: '#ffb37a' },
    { id: 'travel', label: '여행', emoji: '✈️', color: '#5fb3a3' },
    { id: 'daily', label: '일상', emoji: '🛋️', color: '#b79aef' },
    { id: 'sleep', label: '수면', emoji: '💤', color: '#8aa0c9' },
    { id: 'social', label: '인간관계', emoji: '👥', color: '#7ec8e3' },
    { id: 'study', label: '공부', emoji: '📚', color: '#8fd694' },
    { id: 'fun', label: '재미', emoji: '🎉', color: '#ffd166' },
    { id: 'random', label: '랜덤', emoji: '🎲', color: '#ef6a5a' },
  ];

  // ---------- 처방 시드 콘텐츠 (21개, emotion 6종은 app.js SYMPTOMS 어댑터로 별도 제공) ----------
  const PRESCRIPTIONS_SEED = [
    // ---- work ----
    { id: 'work-monday-survival', category: 'work', title: '월요병 생존 주사', diagnosis: '월요병 3기',
      symptom: '월요일 아침만 되면 몸이 무거워지고 눈이 안 떠짐',
      prescription: '이불 밖으로 나온 당신에게 박수를. 커피 한 잔과 함께 천천히 시동을 걸어드립니다',
      sideEffect: '화요일부터는 또 괜찮아짐 (단, 다음 주 월요일 재발 가능)',
      warning: '실제 병가 사유로 사용 시 상사가 처방전을 믿지 않을 수 있어요',
      emoji: '😩', color: '#ff9166', rarity: 'common',
      shareText: '나 지금 월요병 3기래... 너도 처방받아봐 😩💉', isPremium: false },

    { id: 'work-quit-time-craving', category: 'work', title: '퇴근 욕구 과다증', diagnosis: '조기퇴근 갈망 증후군',
      symptom: '출근 30분 만에 시계를 다섯 번 이상 확인함',
      prescription: '남은 시간을 잘게 쪼개어 버틸 수 있게 도와드립니다. 6시가 되면 증상은 기적처럼 사라집니다',
      sideEffect: '지하철역까지 발걸음이 갑자기 빨라질 수 있음',
      warning: '상사 앞에서 처방전을 흔들지 마세요',
      emoji: '🏃', color: '#ffb37a', rarity: 'common',
      shareText: '퇴근 욕구 과다증 처방받고 왔어요 🏃💨', isPremium: false },

    { id: 'work-boss-response', category: 'work', title: '상사 대응 처방', diagnosis: '눈치 과부하 증후군',
      symptom: '상사 목소리만 들려도 어깨가 굳음',
      prescription: '"네, 알겠습니다"를 자연스럽게 발음할 수 있는 텐션을 처방해드립니다',
      sideEffect: '퇴근 후 그 대사가 꿈에 나올 수 있음',
      warning: '실제 반박은 각자 책임입니다',
      emoji: '😐', color: '#9aa8e0', rarity: 'rare',
      shareText: '상사 대응 처방 받고 정신 챙김 😐', isPremium: false },

    { id: 'work-meeting-fatigue', category: 'work', title: '회의 피로 증후군', diagnosis: '이거 이메일로 될 걸 회의로 함 병',
      symptom: '"그래서 결론이 뭐죠"가 목구멍까지 차오름',
      prescription: '회의실 산소 부족 상태에서도 끄덕임을 유지할 수 있는 기력을 보충합니다',
      sideEffect: '다음 회의도 똑같이 늘어질 수 있음',
      warning: '이 처방은 회의 시간 단축을 보장하지 않습니다',
      emoji: '😶', color: '#b79aef', rarity: 'common',
      shareText: '회의 피로 증후군... 나만 그런 거 아니지?', isPremium: false },

    { id: 'work-procrastination', category: 'work', title: '업무 미루기 처방', diagnosis: '내일의 나에게 위임 장애',
      symptom: '마감 전날에만 폭발적인 집중력이 생김',
      prescription: '지금 당장 손가락 하나만 움직이게 하는 최소 동력을 주입합니다',
      sideEffect: '갑자기 책상 정리가 하고 싶어질 수 있음 (가짜 생산성 주의)',
      warning: '실제 마감은 이 주사로 늦춰지지 않습니다',
      emoji: '📎', color: '#ff8fb3', rarity: 'common',
      shareText: '업무 미루기 처방 맞고 일 시작함(진짜임)', isPremium: false },

    // ---- love ----
    { id: 'love-text-urge', category: 'love', title: '연락 충동 억제 주사', diagnosis: '답장 기다림 과열 증후군',
      symptom: '핸드폰을 30초마다 확인하고 있음',
      prescription: '"먼저 연락할까 말까" 사이에서 흔들리는 마음을 진정시켜드립니다',
      sideEffect: '갑자기 쿨한 척 잠수를 타고 싶어질 수 있음',
      warning: '진짜 연락 여부는 본인 판단으로',
      emoji: '📱', color: '#ff9166', rarity: 'rare',
      shareText: '연락 충동 억제 주사 맞고 폰 내려놓음 📱', isPremium: false },

    { id: 'love-read-no-reply', category: 'love', title: '읽씹 후유증 처방', diagnosis: '1이 사라진 자리 증후군',
      symptom: '"읽음" 표시만 보고 하루 종일 딴생각',
      prescription: '상상력을 현실로 착각하지 않도록 마음을 다독여드립니다',
      sideEffect: '답장이 오면 급격히 괜찮아짐',
      warning: '처방 효과는 실제 답장 전까지만 지속됩니다',
      emoji: '💬', color: '#9aa8e0', rarity: 'rare',
      shareText: '읽씹 후유증... 이거 처방 필요해', isPremium: false },

    { id: 'love-blind-date-trauma', category: 'love', title: '소개팅 흑역사 회복 처방', diagnosis: '그때 왜 그 말을 했지 증후군',
      symptom: '갑자기 이불킥하고 싶은 충동이 듦',
      prescription: '지나간 대화는 지나간 대로 흘려보낼 수 있게 도와드립니다',
      sideEffect: '다음 소개팅에서 같은 실수를 반복할 수 있음',
      warning: '완치 아님, 재발 잦음',
      emoji: '🙈', color: '#ef6a5a', rarity: 'epic',
      shareText: '소개팅 흑역사 회복 처방... 만인 필수템', isPremium: false },

    { id: 'love-alone-day', category: 'love', title: '혼자 있고 싶은 날 처방', diagnosis: '사회적 배터리 방전',
      symptom: '아무리 좋아하는 사람도 오늘은 만나기 싫음',
      prescription: '혼자만의 시간을 죄책감 없이 즐길 수 있는 마음을 처방합니다',
      sideEffect: '다음 날 갑자기 사람이 그리워질 수 있음',
      warning: '정상입니다. 걱정 마세요',
      emoji: '🛌', color: '#b79aef', rarity: 'common',
      shareText: '혼자 있고 싶은 날 처방 받는 중 🛌', isPremium: false },

    // ---- food ----
    { id: 'food-chicken-deficiency', category: 'food', title: '치킨 결핍증', diagnosis: '튀김 갈망 3단계',
      symptom: '이유 없이 자꾸 배달 앱을 켜게 됨',
      prescription: '눈으로만 봐도 배부른 치킨 사진 감상 처방을 내려드립니다',
      sideEffect: '결국 시킬 수 있음',
      warning: '실제 배달비는 처방 범위 밖입니다',
      emoji: '🍗', color: '#ffc66b', rarity: 'common',
      shareText: '치킨 결핍증 진단받음... 오늘은 참는다', isPremium: false },

    { id: 'food-late-night-craving', category: 'food', title: '야식 욕구 과다증', diagnosis: '밤 11시 이후 식욕 폭주',
      symptom: '분명 저녁을 먹었는데 또 배가 고픔',
      prescription: '물 한 잔과 함께 "이건 진짜 배고픔이 아니다"라는 최면을 처방합니다',
      sideEffect: '최면 실패 시 라면행',
      warning: '다음 날 아침 체중계가 무서울 수 있음',
      emoji: '🍜', color: '#ff9166', rarity: 'common',
      shareText: '야식 욕구 과다증... 못 참겠다', isPremium: false },

    { id: 'food-coffee-deficiency', category: 'food', title: '커피 부족 증후군', diagnosis: '카페인 혈중 농도 저하',
      symptom: '눈은 떴는데 뇌가 안 켜짐',
      prescription: '각성 상태로 복귀할 수 있도록 가상의 카페인을 주입합니다',
      sideEffect: '진짜 커피를 마시기 전까지는 효과 미미',
      warning: '오후 늦게 처방받으면 밤잠을 설칠 수 있음',
      emoji: '☕', color: '#b98a6f', rarity: 'common',
      shareText: '커피 부족 증후군 처방받고 겨우 눈뜸 ☕', isPremium: false },

    // ---- money ----
    { id: 'money-payday-illusion', category: 'money', title: '월급날 착각 증후군', diagnosis: '내가 부자가 된 줄 아는 병',
      symptom: '월급 찍힌 날 갑자기 씀씀이가 커짐',
      prescription: '통장은 스쳐 지나가는 정거장일 뿐임을 상기시켜드립니다',
      sideEffect: '카드값 명세서 확인 시 급격한 현실 자각',
      warning: '이 처방은 지출을 막아주지 않습니다',
      emoji: '💸', color: '#ffc66b', rarity: 'common',
      shareText: '월급날 착각 증후군 진단 완료 💸', isPremium: false },

    { id: 'money-balance-shock', category: 'money', title: '통장 잔고 쇼크', diagnosis: '잔액 조회 후 심정지 위험군',
      symptom: '앱을 열자마자 눈을 질끈 감게 됨',
      prescription: '숫자를 마주할 용기와 함께 약간의 위로를 처방합니다',
      sideEffect: '확인 후 극단적 절약 모드로 전환될 수 있음',
      warning: '실제 재정 계획은 전문가와 상담하세요 (이 앱은 장난입니다)',
      emoji: '😱', color: '#ef6a5a', rarity: 'rare',
      shareText: '통장 잔고 쇼크... 처방 시급함', isPremium: false },

    { id: 'money-impulse-buy-permit', category: 'money', title: '충동구매 허가증', diagnosis: '장바구니 담기 억제 실패',
      symptom: '"이건 꼭 사야 해"라는 확신이 매일 듦',
      prescription: '오늘 하루만 특별히 허락해드립니다 (내일부터는 각자도생)',
      sideEffect: '택배 도착 후 현타가 올 수 있음',
      warning: '이 허가증은 법적 효력이 없습니다',
      emoji: '🛒', color: '#ff8fb3', rarity: 'epic',
      shareText: '충동구매 허가증 발급받음... 위험하다', isPremium: false },

    // ---- daily ----
    { id: 'daily-do-nothing-syndrome', category: 'daily', title: '아무것도 하기 싫음 증후군', diagnosis: '만사 귀찮음 4기',
      symptom: '물 마시러 가는 것도 미룸',
      prescription: '아무것도 안 해도 괜찮다는 마음의 면죄부를 처방합니다',
      sideEffect: '하루가 순삭될 수 있음',
      warning: '장기 방치 시 배달 음식 쓰레기가 쌓일 수 있음',
      emoji: '🫠', color: '#9aa8e0', rarity: 'common',
      shareText: '만사 귀찮음 4기 처방받고 그냥 누워있음 🫠', isPremium: false },

    { id: 'daily-bed-exit-disorder', category: 'daily', title: '침대 이탈 장애', diagnosis: '이불 중력 과다',
      symptom: '알람을 다섯 번 끄고도 그대로임',
      prescription: '이불 밖으로 한 발짝 내디딜 최소한의 의지를 주입합니다',
      sideEffect: '다시 눕고 싶어질 수 있음',
      warning: '지각 책임은 본인에게 있습니다',
      emoji: '🛏️', color: '#ff9166', rarity: 'common',
      shareText: '침대 이탈 장애 처방받고 겨우 일어남', isPremium: false },

    { id: 'daily-cleaning-avoidance', category: 'daily', title: '청소 회피 증후군', diagnosis: '안 보이면 없는 것 병',
      symptom: '옷더미를 의자라고 우기게 됨',
      prescription: '딱 한 곳만 치울 수 있는 최소 동력을 처방합니다',
      sideEffect: '청소 시작하면 갑자기 대청소로 번질 수 있음',
      warning: '청소 도중 잃어버렸던 물건 발견 시 그리움 유발',
      emoji: '🧹', color: '#5fb3a3', rarity: 'common',
      shareText: '청소 회피 증후군 처방받고 방 치우는 중 🧹', isPremium: false },

    { id: 'daily-weekend-hangover', category: 'daily', title: '주말 후유증', diagnosis: '일요일 저녁 우울',
      symptom: '해가 지면 갑자기 마음이 무거워짐',
      prescription: '월요일이 온다는 사실을 부드럽게 받아들이도록 도와드립니다',
      sideEffect: '갑자기 다음 주말 계획을 세우고 싶어짐',
      warning: '이 증상은 매주 반복됩니다 (정상입니다)',
      emoji: '🌇', color: '#b79aef', rarity: 'common',
      shareText: '일요일 저녁... 주말 후유증 처방 필요', isPremium: false },

    // ---- travel ----
    { id: 'travel-deficiency', category: 'travel', title: '여행 결핍증', diagnosis: '어디든 떠나고 싶음 증후군',
      symptom: '지도 앱을 이유 없이 켜보게 됨',
      prescription: '떠나지 못하는 마음을 여행 사진 감상으로 달래드립니다',
      sideEffect: '결국 항공권 검색까지 이어질 수 있음',
      warning: '통장 잔고와 상의 후 예약하세요',
      emoji: '✈️', color: '#ffc66b', rarity: 'rare',
      shareText: '여행 결핍증 진단... 어디든 떠나고 싶다 ✈️', isPremium: false },

    { id: 'travel-vacation-need', category: 'travel', title: '휴가 필요성 과다증', diagnosis: '연차 소진 지연 위기',
      symptom: '남은 연차를 보며 한숨을 쉼',
      prescription: '지금 당장 캘린더에 연차를 박아 넣을 용기를 처방합니다',
      sideEffect: '상사에게 연차 사유를 설명해야 할 수 있음',
      warning: '연차 승인은 이 앱이 대신 받아주지 않습니다',
      emoji: '🏖️', color: '#ff9166', rarity: 'rare',
      shareText: '휴가 필요성 과다증... 연차 씁니다', isPremium: false },

    // ---- sleep ----
    { id: 'sleep-insomnia-scroll', category: 'sleep', title: '불면의 밤 처방', diagnosis: '누웠는데 정신 말짱 증후군',
      symptom: '불 끄고 누우면 갑자기 온갖 생각이 다 남',
      prescription: '생각 스위치를 서서히 꺼드립니다. 양 대신 처방전 세는 걸 추천드려요',
      sideEffect: '다음 날 알람 소리를 못 들을 수 있음',
      warning: '실제 수면제가 아닙니다',
      emoji: '🌙', color: '#8aa0c9', rarity: 'common',
      shareText: '누웠는데 정신 말짱... 불면 처방 필요함 🌙', isPremium: false },

    { id: 'sleep-naptime-overdose', category: 'sleep', title: '낮잠 남용 처방', diagnosis: '30분 낮잠이 3시간 된 병',
      symptom: '눈떠보니 해가 지고 있음',
      prescription: '죄책감 대신 개운함을 느낄 수 있도록 마음을 다독여드립니다',
      sideEffect: '오늘 밤 다시 불면증 콤보가 발생할 수 있음',
      warning: '낮잠 남용 시 밤낮이 바뀔 수 있습니다',
      emoji: '😴', color: '#7ec8e3', rarity: 'rare',
      shareText: '낮잠 30분이 3시간 됨... 이거 병인가요', isPremium: false },

    { id: 'sleep-nightowl', category: 'sleep', title: '올빼미 전환 처방', diagnosis: '밤 12시부터 눈이 초롱초롱 증후군',
      symptom: '낮엔 좀비, 밤엔 쌩쌩함',
      prescription: '내일의 나에게 미안함을 잠시 잊게 해드립니다',
      sideEffect: '다음 날 카페인 부족 증후군과 콤보로 발생할 수 있음',
      warning: '출근 시간은 이 처방으로 조정되지 않습니다',
      emoji: '🦉', color: '#b79aef', rarity: 'epic',
      shareText: '밤 12시부터 눈이 초롱초롱... 올빼미 확정', isPremium: false },

    // ---- social (인간관계) ----
    { id: 'social-groupchat-lurker', category: 'social', title: '단톡방 눈팅 처방', diagnosis: '낄 타이밍 상실 증후군',
      symptom: '메시지는 다 읽었는데 낄 타이밍을 영영 놓침',
      prescription: '"ㅋㅋㅋ" 하나라도 보낼 수 있는 용기를 처방합니다',
      sideEffect: '타이밍 놓친 드립이 3일 후에 생각날 수 있음',
      warning: '실제 대화 참여는 본인 몫입니다',
      emoji: '👀', color: '#7ec8e3', rarity: 'common',
      shareText: '단톡방 눈팅만 3일째... 처방 필요함 👀', isPremium: false },

    { id: 'social-awkward-aftermath', category: 'social', title: '갑분싸 회복 처방', diagnosis: '방금 그 말 왜 했지 증후군',
      symptom: '집에 오는 길에 갑자기 이불킥하고 싶어짐',
      prescription: '지나간 정적은 지나간 대로 흘려보내는 마음을 처방합니다',
      sideEffect: '다음 만남에서 똑같은 실수를 반복할 수 있음',
      warning: '완치 아님, 평생 함께 갈 수 있음',
      emoji: '😬', color: '#8aa0c9', rarity: 'rare',
      shareText: '갑분싸 회복 처방 받는 중... 이불킥 방지', isPremium: false },

    { id: 'social-detox-urge', category: 'social', title: '인맥 디톡스 처방', diagnosis: '연락 다 끊고 싶음 증후군',
      symptom: '핸드폰 연락처를 보다가 한숨이 나옴',
      prescription: '잠시 혼자만의 시간을 가져도 괜찮다는 마음을 처방합니다',
      sideEffect: '며칠 뒤 다시 사람이 그리워질 수 있음',
      warning: '실제 연락처 삭제는 신중히 결정하세요',
      emoji: '🚪', color: '#b79aef', rarity: 'epic',
      shareText: '인맥 디톡스 처방... 연락 다 끊고 싶다', isPremium: false },

    // ---- study (공부) ----
    { id: 'study-cram-chronic', category: 'study', title: '벼락치기 만성 처방', diagnosis: '전날에만 집중력 폭발 증후군',
      symptom: '시험 3일 전엔 여유롭다가 전날 밤 갑자기 초인이 됨',
      prescription: '지금 이 순간의 집중력을 최대한 오래 유지시켜드립니다',
      sideEffect: '시험 끝나자마자 방전될 수 있음',
      warning: '평소 공부는 이 처방으로 대체되지 않습니다',
      emoji: '🔥', color: '#8fd694', rarity: 'common',
      shareText: '벼락치기 만성... 오늘 밤도 초인모드 🔥', isPremium: false },

    { id: 'study-distraction', category: 'study', title: '책상 앞 딴짓 처방', diagnosis: '책만 펴면 청소하고 싶은 병',
      symptom: '공부 시작 3분 만에 책상 정리를 시작함',
      prescription: '가짜 생산성 대신 진짜 집중으로 방향을 잡아드립니다',
      sideEffect: '방은 깨끗해지지만 진도는 그대로일 수 있음',
      warning: '정리정돈은 공부가 아닙니다 (본인도 이미 알고 있음)',
      emoji: '🧽', color: '#7ec8e3', rarity: 'rare',
      shareText: '책상 정리만 하다 30분 지남... 처방 급함', isPremium: false },

    { id: 'study-exam-anxiety', category: 'study', title: '시험 전날 불안 처방', diagnosis: '아는 것도 까먹을 것 같은 공포',
      symptom: '분명 아는 문제인데 시험지만 보면 하얘질 것 같음',
      prescription: '아는 만큼은 확실히 나온다는 믿음을 처방합니다',
      sideEffect: '시험 끝나고 나서야 답이 생각날 수 있음',
      warning: '실제 성적은 이 처방과 무관합니다',
      emoji: '😰', color: '#ef6a5a', rarity: 'epic',
      shareText: '시험 전날 불안 처방... 제발 다 기억나라', isPremium: false },

    // ---- fun (재미) ----
    { id: 'fun-laughter-deficiency', category: 'fun', title: '웃음 결핍 처방', diagnosis: '요즘 크게 웃은 적 없음 증후군',
      symptom: '재밌는 걸 봐도 피식 정도밖에 안 나옴',
      prescription: '아무 이유 없이 웃을 수 있는 여유를 처방합니다',
      sideEffect: '갑자기 옛날 짤을 정주행하고 싶어질 수 있음',
      warning: '웃참 실패 시 주변 시선은 책임지지 않습니다',
      emoji: '😂', color: '#ffd166', rarity: 'common',
      shareText: '요즘 크게 웃은 적이 없어서 처방받음 😂', isPremium: false },

    { id: 'fun-productivity-guilt', category: 'fun', title: '갓생 강박 해소 처방', diagnosis: '놀아도 죄책감 드는 병',
      symptom: '쉬는 중에도 뭔가 해야 할 것 같은 불안',
      prescription: '오늘 하루쯤은 그냥 놀아도 된다는 허락을 내려드립니다',
      sideEffect: '허락받은 김에 계획 없이 하루를 다 쓸 수 있음',
      warning: '내일의 갓생은 내일의 내가 알아서 합니다',
      emoji: '🛋️', color: '#ffc66b', rarity: 'rare',
      shareText: '놀아도 죄책감... 갓생 강박 처방 받음', isPremium: false },

    { id: 'fun-shorts-addiction', category: 'fun', title: '숏폼 무한스크롤 처방', diagnosis: '릴스 3개만 보려다 1시간 증후군',
      symptom: '정신 차려보면 손가락이 알아서 넘기고 있음',
      prescription: '"딱 하나만 더"의 늪에서 잠시 빠져나올 힘을 드립니다',
      sideEffect: '금단 현상으로 무의식적 손가락 스와이프가 남을 수 있음',
      warning: '알고리즘의 유혹은 이 처방보다 강할 수 있습니다',
      emoji: '📱', color: '#ef6a5a', rarity: 'epic',
      shareText: '릴스 3개만 보려다 1시간... 숏폼 중독 확정', isPremium: false },
    { id: 'work-inbox-flood', category: 'work', title: '메일함 범람 증후군', diagnosis: '받은편지함 과부하',
      symptom: '읽지 않은 메일 숫자만 봐도 숨이 막힘',
      prescription: '위에서 세 통만 처리하세요. 나머지는 오늘의 당신 몫이 아닙니다',
      sideEffect: '숫자가 줄어드는 걸 보고 쾌감을 느낄 수 있음',
      warning: '전체 선택 후 읽음 처리는 나중에 후회할 수 있어요',
      emoji: '📬', color: '#8aa0c9', rarity: 'common',
      shareText: '받은편지함 과부하래... 너도 열어보기 무섭지 📬💉', isPremium: false },
    { id: 'work-meeting-mute', category: 'work', title: '마이크 켠 줄 모름 증후군', diagnosis: '화상회의 후유증',
      symptom: '회의 끝나고 무슨 말을 했는지 하나도 기억 안 남',
      prescription: '카메라 끄고 3분만 멍하니 있어도 됩니다. 다음 회의 전까지는 아직 시간이 있어요',
      sideEffect: '회의록을 다시 읽으며 내가 한 말에 놀랄 수 있음',
      warning: '실제로 마이크가 켜져 있었는지는 확인해드릴 수 없어요',
      emoji: '🎙️', color: '#9aa8e0', rarity: 'common',
      shareText: '화상회의 후유증 3기 진단받음 🎙️💉', isPremium: false },
    { id: 'work-friday-ghost', category: 'work', title: '금요일 영혼 가출증', diagnosis: '주말 선행 이탈',
      symptom: '금요일 오후 2시부터 몸만 자리에 있음',
      prescription: '이미 반은 주말입니다. 남은 반나절은 가벼운 것부터 치우세요',
      sideEffect: '월요일에 미뤄둔 일과 재회하게 됨',
      warning: '퇴근 시간 전 이탈은 처방전으로 정당화되지 않아요',
      emoji: '🫥', color: '#ffc66b', rarity: 'common',
      shareText: '금요일 영혼 가출증이래 🫥💉', isPremium: false },
    { id: 'work-praise-drought', category: 'work', title: '칭찬 결핍증', diagnosis: '인정 욕구 미충족',
      symptom: '열심히 했는데 아무도 모르는 것 같음',
      prescription: '오늘 한 일을 세 줄로 적어두세요. 아무도 안 알아줘도 기록은 남습니다',
      sideEffect: '적어놓고 보니 생각보다 많이 했다는 걸 알게 됨',
      warning: '그 기록을 상사에게 그대로 보내는 건 타이밍을 보세요',
      emoji: '🏅', color: '#ffd166', rarity: 'rare',
      shareText: '칭찬 결핍증 확정 🏅💉', isPremium: false },
    { id: 'work-slack-ping', category: 'work', title: '알림 소리 공포증', diagnosis: '상시 대기 상태',
      symptom: '메신저 알림음만 들려도 심장이 먼저 반응함',
      prescription: '알림을 30분만 꺼두세요. 그 사이에 세상은 안 망합니다',
      sideEffect: '30분 뒤 쌓인 알림을 보고 다시 놀랄 수 있음',
      warning: '중요한 연락이 올 수 있으니 시간은 본인이 정하세요',
      emoji: '🔔', color: '#ef6a5a', rarity: 'common',
      shareText: '알림 소리 공포증이래... 나만 그래? 🔔💉', isPremium: false },
    { id: 'love-old-photo', category: 'love', title: '옛날 사진 스크롤 증후군', diagnosis: '과거 재방문',
      symptom: '자기 전에 굳이 예전 사진첩을 열어봄',
      prescription: '다 본 다음에 한 장만 남기고 나머지는 닫으세요. 오늘은 거기까지',
      sideEffect: '다음 날 아침에 왜 그랬지 싶어짐',
      warning: '새벽 3시의 판단력은 처방 대상이 아닙니다',
      emoji: '🖼️', color: '#ff8fb3', rarity: 'common',
      shareText: '옛날 사진 스크롤 증후군... 다들 이러지 않아요? 🖼️💉', isPremium: false },
    { id: 'love-first-message', category: 'love', title: '첫 메시지 백 번 고침', diagnosis: '전송 직전 증후군',
      symptom: '보내기 전에 지웠다 썼다를 반복함',
      prescription: '처음 쓴 걸 그냥 보내세요. 백 번째 버전이 첫 번째보다 나은 경우는 드뭅니다',
      sideEffect: '보내고 나면 의외로 별일 아니었다는 걸 알게 됨',
      warning: '새벽 전송은 내용과 무관하게 감점 요인이 될 수 있어요',
      emoji: '✍️', color: '#ffb37a', rarity: 'common',
      shareText: '첫 메시지 백 번 고치는 중 ✍️💉', isPremium: false },
    { id: 'love-anniversary-panic', category: 'love', title: '기념일 임박 공황', diagnosis: '날짜 인지 지연',
      symptom: '달력을 보고 나서야 알게 됨',
      prescription: '지금 준비해도 늦지 않았습니다. 비싼 것보다 기억하고 있다는 신호가 먼저예요',
      sideEffect: '내년에도 같은 날 같은 증상이 재발함',
      warning: '잊은 걸 들키는 것보다 늦게라도 챙기는 쪽이 낫습니다',
      emoji: '📆', color: '#ff8fb3', rarity: 'common',
      shareText: '기념일 임박 공황 왔다 📆💉', isPremium: false },
    { id: 'love-friend-zone', category: 'love', title: '애매한 사이 해석 장애', diagnosis: '신호 판독 불가',
      symptom: '상대가 보낸 이모티콘 하나를 삼십 분째 분석 중',
      prescription: '분석을 멈추고 직접 물어보는 쪽이 빠릅니다. 아니면 오늘은 덮어두세요',
      sideEffect: '답이 오면 분석할 거리가 하나 더 생김',
      warning: '해석 결과는 본인 책임입니다',
      emoji: '🔍', color: '#b79aef', rarity: 'rare',
      shareText: '애매한 사이 해석 장애 판정 🔍💉', isPremium: false },
    { id: 'love-alone-fine', category: 'love', title: '혼자도 괜찮음 증명 욕구', diagnosis: '과잉 방어',
      symptom: '괜찮다고 여러 번 말하고 있음',
      prescription: '여러 번 말했다면 한 번쯤은 안 괜찮아도 됩니다. 오늘만 인정해주세요',
      sideEffect: '말하고 나면 오히려 편해질 수 있음',
      warning: '괜찮지 않다고 해서 지는 게 아닙니다',
      emoji: '🫧', color: '#7ec8e3', rarity: 'common',
      shareText: '혼자도 괜찮음 증명 욕구... 나만 그런가 🫧💉', isPremium: false },
    { id: 'love-read-late', category: 'love', title: '답장 타이밍 계산기', diagnosis: '의도적 지연',
      symptom: '바로 읽고 세 시간 뒤에 답하려고 타이머를 맞춤',
      prescription: '읽었으면 그냥 답하세요. 계산한 티는 생각보다 잘 납니다',
      sideEffect: '계산 없이 답했더니 대화가 더 길어질 수 있음',
      warning: '상대도 같은 계산을 하고 있을 수 있어요',
      emoji: '⏱️', color: '#ffb37a', rarity: 'common',
      shareText: '답장 타이밍 계산 중입니다 ⏱️💉', isPremium: false },
    { id: 'money-delivery-fee', category: 'money', title: '배달비 분노 조절 장애', diagnosis: '마지막 화면 충격',
      symptom: '음식값보다 배달비에 더 화가 남',
      prescription: '오늘은 그냥 시키세요. 나가서 사 오는 시간도 값입니다',
      sideEffect: '다음 주문에서도 같은 화면에서 같은 감정을 겪음',
      warning: '최소주문금액을 맞추려 더 시키는 건 처방 범위 밖입니다',
      emoji: '🛵', color: '#ff9166', rarity: 'common',
      shareText: '배달비 분노 조절 장애 3기 🛵💉', isPremium: false },
    { id: 'money-subscription-leak', category: 'money', title: '구독료 누수 증후군', diagnosis: '자동결제 망각',
      symptom: '뭘 구독했는지 본인도 모름',
      prescription: '결제 내역 한 화면만 열어보세요. 하나만 정리해도 성공입니다',
      sideEffect: '해지하고 나면 그게 뭐였는지도 기억 안 남',
      warning: '해지 후 재가입 시 할인은 사라질 수 있어요',
      emoji: '🧾', color: '#5fb3a3', rarity: 'common',
      shareText: '구독료 누수 증후군 확정 🧾💉', isPremium: false },
    { id: 'money-payday-echo', category: 'money', title: '월급 잔상 증후군', diagnosis: '입금 후 3일차',
      symptom: '분명 들어왔는데 벌써 얼마 안 남음',
      prescription: '어디로 갔는지 세 건만 찾아보세요. 나머지는 안 봐도 됩니다',
      sideEffect: '찾다 보면 하나쯤은 기억에 없을 수 있음',
      warning: '전액 추적은 정신 건강에 해로울 수 있어요',
      emoji: '💸', color: '#ffc66b', rarity: 'common',
      shareText: '월급 잔상 증후군... 벌써 없어 💸💉', isPremium: false },
    { id: 'money-cart-graveyard', category: 'money', title: '장바구니 묘지 관리사', diagnosis: '결제 보류 누적',
      symptom: '담아만 두고 석 달째 방치 중',
      prescription: '오늘은 하나만 결제하거나 전부 비우세요. 중간은 없습니다',
      sideEffect: '비우고 나면 뭐가 있었는지도 잊음',
      warning: '품절은 기다려주지 않습니다',
      emoji: '🛒', color: '#b79aef', rarity: 'common',
      shareText: '장바구니 묘지 관리 중 🛒💉', isPremium: false },
    { id: 'money-friend-split', category: 'money', title: '더치페이 계산 피로', diagnosis: '정산 담당 번아웃',
      symptom: '매번 계산하고 매번 먼저 냄',
      prescription: '오늘은 계산기를 남에게 넘기세요. 한 번쯤은 받는 쪽에 있어도 됩니다',
      sideEffect: '넘기고 나면 의외로 아무 일도 안 생김',
      warning: '받을 돈 독촉은 이 처방으로 해결되지 않아요',
      emoji: '🧮', color: '#8aa0c9', rarity: 'common',
      shareText: '더치페이 계산 피로 왔다 🧮💉', isPremium: false },
    { id: 'money-saving-guilt', category: 'money', title: '안 쓰고도 불안증', diagnosis: '절약 후 공허',
      symptom: '아꼈는데 기분이 안 좋음',
      prescription: '아낀 돈의 10%만 오늘 쓰세요. 그게 절약을 오래 가게 합니다',
      sideEffect: '쓰고 나서도 또 불안해질 수 있음',
      warning: '10%의 기준은 본인이 정하는 겁니다',
      emoji: '🪙', color: '#ffd166', rarity: 'rare',
      shareText: '안 쓰고도 불안증 진단 🪙💉', isPremium: false },
    { id: 'money-invest-refresh', category: 'money', title: '시세 새로고침 강박', diagnosis: '확인 주기 단축',
      symptom: '5분마다 같은 숫자를 다시 봄',
      prescription: '앱을 홈 화면 두 번째 페이지로 옮기세요. 그것만으로 횟수가 줄어듭니다',
      sideEffect: '줄어든 횟수만큼 다른 걸 새로고침하게 될 수 있음',
      warning: '투자 판단에 대한 조언은 아닙니다',
      emoji: '📉', color: '#ef6a5a', rarity: 'common',
      shareText: '시세 새로고침 강박 🔁📉💉', isPremium: false },
    { id: 'food-midnight-menu', category: 'food', title: '자정 메뉴 결정 장애', diagnosis: '선택 지연',
      symptom: '배는 고픈데 뭘 먹을지 30분째 고민 중',
      prescription: '고민한 시간이 아깝습니다. 처음 떠오른 걸 시키세요',
      sideEffect: '다음 날 같은 시간에 같은 고민이 반복됨',
      warning: '고민 끝에 안 먹는 것도 선택지입니다',
      emoji: '🌙', color: '#9aa8e0', rarity: 'common',
      shareText: '자정 메뉴 결정 장애 🌙💉', isPremium: false },
    { id: 'food-spicy-regret', category: 'food', title: '매운맛 과신 증후군', diagnosis: '한계 오판',
      symptom: '항상 제일 매운 단계를 고르고 후회함',
      prescription: '우유 한 잔 먼저 준비하세요. 다음엔 한 단계 내려도 자존심 안 상합니다',
      sideEffect: '내일 아침에 한 번 더 후회할 수 있음',
      warning: '위가 약한 분은 처방 전에 본인 판단이 우선입니다',
      emoji: '🌶️', color: '#ef6a5a', rarity: 'common',
      shareText: '매운맛 과신 증후군 또 걸림 🌶️💉', isPremium: false },
    { id: 'food-diet-tomorrow', category: 'food', title: '내일부터 다이어트증', diagnosis: '시작일 무한 연기',
      symptom: '어제도 내일부터였음',
      prescription: '오늘 한 끼만 가볍게 하세요. 시작일을 정하는 것보다 그게 빠릅니다',
      sideEffect: '내일도 같은 처방이 필요할 수 있음',
      warning: '체중 변화를 보장하지 않습니다',
      emoji: '📅', color: '#8fd694', rarity: 'common',
      shareText: '내일부터 다이어트증 만성화 📅💉', isPremium: false },
    { id: 'food-leftover-guilt', category: 'food', title: '남은 음식 죄책감', diagnosis: '잔반 처리 압박',
      symptom: '배부른데 남기는 게 죄 같아서 계속 먹음',
      prescription: '그릇을 비우는 건 의무가 아닙니다. 지금 젓가락을 놓아도 괜찮아요',
      sideEffect: '다음 끼니가 덜 부담스러워짐',
      warning: '상하기 전에 보관은 따로 챙기세요',
      emoji: '🍚', color: '#b98a6f', rarity: 'common',
      shareText: '남은 음식 죄책감... 나만 그래? 🍚💉', isPremium: false },
    { id: 'food-cafe-hop', category: 'food', title: '카페 디저트 합리화', diagnosis: '당 충전 명분',
      symptom: '오늘은 고생했으니까 먹어도 된다고 생각 중',
      prescription: '고생한 건 사실입니다. 오늘은 그 명분을 그냥 쓰세요',
      sideEffect: '내일도 고생할 예정이라 명분은 계속 생김',
      warning: '명분의 재사용 횟수는 제한하지 않습니다',
      emoji: '🍰', color: '#ff8fb3', rarity: 'common',
      shareText: '카페 디저트 합리화 완료 🍰💉', isPremium: false },
    { id: 'food-water-neglect', category: 'food', title: '물 안 마심 증후군', diagnosis: '수분 기록 0',
      symptom: '커피만 마시고 물은 하루 한 잔',
      prescription: '지금 한 컵만 마시세요. 그게 오늘의 처방 전부입니다',
      sideEffect: '화장실 가는 횟수가 늘어날 수 있음',
      warning: '커피는 물에 포함되지 않습니다',
      emoji: '🚰', color: '#7ec8e3', rarity: 'common',
      shareText: '물 안 마심 증후군 진단 🚰💉', isPremium: false },
    { id: 'food-fridge-open', category: 'food', title: '냉장고 반복 개방증', diagnosis: '기대 재확인',
      symptom: '10분 전과 같은 내용물을 또 확인함',
      prescription: '냉장고는 닫고 물이나 한 잔 하세요. 배고픔이 아니라 심심함일 수 있습니다',
      sideEffect: '심심함이 확인되면 다른 처방이 필요해짐',
      warning: '전기요금은 책임지지 않습니다',
      emoji: '🧊', color: '#8aa0c9', rarity: 'common',
      shareText: '냉장고 반복 개방증 🧊💉', isPremium: false },
    { id: 'travel-window-stare', category: 'travel', title: '창밖 응시 증후군', diagnosis: '떠남 욕구 누적',
      symptom: '일하다 말고 창밖만 보고 있음',
      prescription: '오늘 퇴근길에 한 정거장 먼저 내려 걸어보세요. 작은 이동도 이동입니다',
      sideEffect: '한 정거장으로는 부족하다는 걸 알게 됨',
      warning: '무단 조퇴는 처방에 포함되지 않습니다',
      emoji: '🪟', color: '#7ec8e3', rarity: 'common',
      shareText: '창밖 응시 증후군 🪟💉', isPremium: false },
    { id: 'travel-ticket-window', category: 'travel', title: '항공권 검색만 증후군', diagnosis: '예약 직전 이탈',
      symptom: '매일 검색하고 결제는 안 함',
      prescription: '오늘은 날짜만 하나 정해두세요. 결제는 내일 해도 됩니다',
      sideEffect: '날짜를 정하면 가격이 보이기 시작함',
      warning: '가격 변동은 처방과 무관합니다',
      emoji: '🛫', color: '#8aa0c9', rarity: 'common',
      shareText: '항공권 검색만 3개월째 🛫💉', isPremium: false },
    { id: 'travel-packing-panic', category: 'travel', title: '짐 싸기 회피증', diagnosis: '출발 전날 증후군',
      symptom: '캐리어는 폈는데 아무것도 안 넣음',
      prescription: '속옷과 충전기만 먼저 넣으세요. 나머지는 현지에서도 구할 수 있습니다',
      sideEffect: '현지에서 사면서 또 짐이 늘어남',
      warning: '여권은 이 처방으로 대체되지 않습니다',
      emoji: '🧳', color: '#ffc66b', rarity: 'common',
      shareText: '짐 싸기 회피증 발동 🧳💉', isPremium: false },
    { id: 'travel-photo-backlog', category: 'travel', title: '사진 정리 미룸증', diagnosis: '여행 후 3개월',
      symptom: '갔다 온 사진을 아직 안 봄',
      prescription: '오늘은 열 장만 보세요. 좋았던 하루가 다시 떠오를 겁니다',
      sideEffect: '보다 보면 또 가고 싶어짐',
      warning: '전체 정리는 오늘 목표가 아닙니다',
      emoji: '📷', color: '#b98a6f', rarity: 'common',
      shareText: '사진 정리 미룸증 3개월차 📷💉', isPremium: false },
    { id: 'travel-map-wander', category: 'travel', title: '지도 앱 배회증', diagnosis: '목적지 없는 탐색',
      symptom: '가지도 않을 도시를 확대해서 보고 있음',
      prescription: '그중 한 곳을 메모에 적어두세요. 언젠가 가게 되면 그게 시작점입니다',
      sideEffect: '적어둔 목록이 계속 길어짐',
      warning: '실제 방문을 보장하지 않습니다',
      emoji: '🗺️', color: '#5fb3a3', rarity: 'common',
      shareText: '지도 앱 배회증 🗺️💉', isPremium: false },
    { id: 'travel-monday-return', category: 'travel', title: '여행 복귀 충격', diagnosis: '일상 재진입 실패',
      symptom: '돌아온 다음 날이 제일 힘듦',
      prescription: '오늘은 평소의 70%만 하세요. 복귀에도 적응 시간이 필요합니다',
      sideEffect: '다음 여행 계획을 세우게 될 수 있음',
      warning: '연차 추가 사용은 본인 재량입니다',
      emoji: '🏠', color: '#9aa8e0', rarity: 'common',
      shareText: '여행 복귀 충격 왔다 🏠💉', isPremium: false },
    { id: 'travel-near-trip', category: 'travel', title: '가까운 데 못 감 증후군', diagnosis: '거리 기준 왜곡',
      symptom: '해외만 여행이라고 생각 중',
      prescription: '버스로 한 시간 거리에도 안 가본 곳이 있습니다. 이번 주말에 하나만',
      sideEffect: '가까운 곳이 의외로 좋을 수 있음',
      warning: '기대치 조정은 본인 몫입니다',
      emoji: '🚌', color: '#8fd694', rarity: 'common',
      shareText: '가까운 데 못 감 증후군 🚌💉', isPremium: false },
    { id: 'travel-solo-fear', category: 'travel', title: '혼자 여행 망설임', diagnosis: '동행 대기 상태',
      symptom: '같이 갈 사람이 없어서 계속 미룸',
      prescription: '반나절짜리로 한 번만 혼자 가보세요. 생각보다 편할 수 있습니다',
      sideEffect: '혼자가 더 편하다는 걸 알게 될 위험이 있음',
      warning: '안전한 장소와 시간은 본인이 고르세요',
      emoji: '🚶', color: '#b79aef', rarity: 'rare',
      shareText: '혼자 여행 망설임 진단 🚶💉', isPremium: false },
    { id: 'daily-laundry-mountain', category: 'daily', title: '빨래 산맥 형성증', diagnosis: '건조대 점거',
      symptom: '마른 빨래가 건조대에서 일주일째 거주 중',
      prescription: '양말만 먼저 개세요. 시작하면 나머지도 따라옵니다',
      sideEffect: '개고 나면 다음 빨래가 이미 돌아가고 있음',
      warning: '옷장 정리까지는 오늘 목표가 아닙니다',
      emoji: '🧺', color: '#8fd694', rarity: 'common',
      shareText: '빨래 산맥 형성증 🧺💉', isPremium: false },
    { id: 'daily-dish-tower', category: 'daily', title: '설거지 탑 축조증', diagnosis: '싱크대 과밀',
      symptom: '컵부터 시작해서 탑이 됨',
      prescription: '물에 담가만 두세요. 그것도 오늘의 진전입니다',
      sideEffect: '내일의 나에게 넘어가지만 조금은 쉬워짐',
      warning: '탑의 높이는 처방으로 낮아지지 않습니다',
      emoji: '🍽️', color: '#b98a6f', rarity: 'common',
      shareText: '설거지 탑 축조 중 🍽️💉', isPremium: false },
    { id: 'daily-shower-delay', category: 'daily', title: '샤워 진입 지연증', diagnosis: '시작 문턱 상승',
      symptom: '씻어야 하는 건 아는데 몸이 안 움직임',
      prescription: '수건만 꺼내놓으세요. 그다음은 대체로 저절로 됩니다',
      sideEffect: '씻고 나면 진작 할걸 싶어짐',
      warning: '미룬 시간은 돌려드리지 못합니다',
      emoji: '🚿', color: '#7ec8e3', rarity: 'common',
      shareText: '샤워 진입 지연증 🚿💉', isPremium: false },
    { id: 'daily-doom-scroll', category: 'daily', title: '누운 채 스크롤증', diagnosis: '기상 실패 지속',
      symptom: '일어났는데 30분째 누워서 폰만 봄',
      prescription: '발만 먼저 바닥에 대보세요. 몸은 대체로 따라옵니다',
      sideEffect: '일어나면 왜 누워 있었나 싶어짐',
      warning: '알람 추가 설정은 해결책이 아닙니다',
      emoji: '📱', color: '#9aa8e0', rarity: 'common',
      shareText: '누운 채 스크롤증 확정 📱💉', isPremium: false },
    { id: 'daily-plant-guilt', category: 'daily', title: '화분 죄책감', diagnosis: '관리 실패 누적',
      symptom: '또 하나 보냈음',
      prescription: '살아 있는 것부터 물 주세요. 떠난 건 당신 탓만은 아닙니다',
      sideEffect: '새로 들이면 같은 일이 반복될 수 있음',
      warning: '식물 종류별 관리법은 따로 알아보세요',
      emoji: '🪴', color: '#8fd694', rarity: 'common',
      shareText: '화분 죄책감... 또 보냈어 🪴💉', isPremium: false },
    { id: 'daily-receipt-pile', category: 'daily', title: '서랍 속 잡동사니증', diagnosis: '보관 기준 부재',
      symptom: '언젠가 쓸 것 같아서 못 버림',
      prescription: '한 칸만 비우세요. 전체를 하려다 아무것도 못 합니다',
      sideEffect: '비운 자리에 새 잡동사니가 생김',
      warning: '버린 물건의 재구매는 책임지지 않습니다',
      emoji: '🗄️', color: '#8aa0c9', rarity: 'common',
      shareText: '서랍 속 잡동사니증 🗄️💉', isPremium: false },
    { id: 'sleep-alarm-snooze', category: 'sleep', title: '알람 연속 해제증', diagnosis: '기상 지연 반복',
      symptom: '5분씩 여섯 번 미룸',
      prescription: '알람을 한 번만 맞추세요. 여러 개는 오히려 잠을 조각냅니다',
      sideEffect: '처음엔 더 못 일어날 수 있음',
      warning: '지각에 대한 책임은 지지 않습니다',
      emoji: '⏰', color: '#ffc66b', rarity: 'common',
      shareText: '알람 연속 해제증 6회 ⏰💉', isPremium: false },
    { id: 'sleep-overthink-night', category: 'sleep', title: '자기 전 회상 증후군', diagnosis: '취침 직전 재생',
      symptom: '3년 전 일이 왜 지금 떠오르는지 모르겠음',
      prescription: '떠오르는 걸 막지 말고 메모에 한 줄만 적으세요. 적으면 머리에서 나갑니다',
      sideEffect: '다른 기억이 이어서 떠오를 수 있음',
      warning: '기억의 순서는 조정해드릴 수 없습니다',
      emoji: '💭', color: '#b79aef', rarity: 'rare',
      shareText: '자기 전 회상 증후군 💭💉', isPremium: false },
    { id: 'sleep-weekend-shift', category: 'sleep', title: '주말 시차 증후군', diagnosis: '수면 리듬 이동',
      symptom: '토요일에 늦게 자고 일요일 밤에 못 잠',
      prescription: '일요일 아침만 평소 시간에 일어나세요. 밤은 알아서 따라옵니다',
      sideEffect: '토요일의 즐거움이 조금 줄어듦',
      warning: '낮잠으로 보충하면 원위치됩니다',
      emoji: '🛏️', color: '#9aa8e0', rarity: 'common',
      shareText: '주말 시차 증후군 🛏️💉', isPremium: false },
    { id: 'sleep-phone-bed', category: 'sleep', title: '머리맡 폰 의존증', diagnosis: '취침 환경 오염',
      symptom: '자다 깨서도 시간을 확인함',
      prescription: '폰을 팔이 안 닿는 곳에 두세요. 거리만으로 횟수가 줄어듭니다',
      sideEffect: '처음 며칠은 불안할 수 있음',
      warning: '알람용이라면 다른 기기를 쓰세요',
      emoji: '🌜', color: '#8aa0c9', rarity: 'common',
      shareText: '머리맡 폰 의존증 🌜💉', isPremium: false },
    { id: 'sleep-nap-overrun', category: 'sleep', title: '낮잠 초과 착지', diagnosis: '20분이 2시간',
      symptom: '깨어나니 해가 져 있음',
      prescription: '일어나서 햇빛만 5분 쬐세요. 밤잠을 그나마 건집니다',
      sideEffect: '그래도 밤에 안 졸릴 수 있음',
      warning: '다음 날 컨디션은 보장하지 않습니다',
      emoji: '☀️', color: '#ffd166', rarity: 'common',
      shareText: '낮잠 초과 착지... 해가 졌어 ☀️💉', isPremium: false },
    { id: 'sleep-dream-tired', category: 'sleep', title: '꿈에서도 일함증', diagnosis: '수면 중 근무',
      symptom: '자고 일어나도 일한 기분',
      prescription: '자기 전 30분은 화면을 끄세요. 머리에 일감을 넣지 않는 게 먼저입니다',
      sideEffect: '꿈의 내용까지는 조정되지 않음',
      warning: '초과근무 수당 청구는 불가합니다',
      emoji: '😴', color: '#5fb3a3', rarity: 'common',
      shareText: '꿈에서도 일함증 진단 😴💉', isPremium: false },
    { id: 'sleep-early-fail', category: 'sleep', title: '일찍 자기 실패증', diagnosis: '계획과 현실 괴리',
      symptom: '11시에 누웠는데 2시에 잠듦',
      prescription: '눕는 시간이 아니라 화면 끄는 시간을 당기세요',
      sideEffect: '처음엔 천장만 보게 될 수 있음',
      warning: '수면제와는 무관한 처방입니다',
      emoji: '🕚', color: '#b79aef', rarity: 'common',
      shareText: '일찍 자기 실패증 🕚💉', isPremium: false },
    { id: 'social-reply-debt', category: 'social', title: '답장 빚 누적증', diagnosis: '미응답 부채',
      symptom: '읽고 안 한 답장이 쌓여서 더 못 하겠음',
      prescription: '제일 오래된 것 하나만 하세요. \'늦어서 미안\'으로 시작하면 됩니다',
      sideEffect: '한 개를 하면 나머지도 쉬워짐',
      warning: '전부 오늘 할 필요는 없습니다',
      emoji: '📮', color: '#ffb37a', rarity: 'common',
      shareText: '답장 빚 누적증 📮💉', isPremium: false },
    { id: 'social-group-invite', category: 'social', title: '모임 초대 부담증', diagnosis: '거절 난이도 상승',
      symptom: '가기 싫은데 거절이 더 어려움',
      prescription: '\'이번엔 어려울 것 같아\'면 충분합니다. 이유는 안 붙여도 됩니다',
      sideEffect: '다음 초대가 줄어들 수 있음',
      warning: '관계 유지는 본인 판단입니다',
      emoji: '🚪', color: '#8aa0c9', rarity: 'common',
      shareText: '모임 초대 부담증 🚪💉', isPremium: false },
    { id: 'social-sns-compare', category: 'social', title: '피드 비교 후유증', diagnosis: '타인 하이라이트 과다 노출',
      symptom: '다들 잘 사는 것 같아서 기분이 가라앉음',
      prescription: '피드를 10분만 닫고 오늘 내가 한 일 하나를 떠올리세요',
      sideEffect: '닫아도 다시 열게 될 수 있음',
      warning: '계정 삭제까지는 권하지 않습니다',
      emoji: '📊', color: '#b79aef', rarity: 'common',
      shareText: '피드 비교 후유증 📊💉', isPremium: false },
    { id: 'social-small-talk', category: 'social', title: '스몰토크 고갈증', diagnosis: '화제 재고 소진',
      symptom: '날씨 얘기 다음이 안 떠오름',
      prescription: '질문 하나만 준비하세요. 말하는 것보다 묻는 쪽이 편합니다',
      sideEffect: '질문이 길어지면 면접처럼 될 수 있음',
      warning: '대화의 성공을 보장하지 않습니다',
      emoji: '💬', color: '#5fb3a3', rarity: 'common',
      shareText: '스몰토크 고갈증 💬💉', isPremium: false },
    { id: 'social-old-friend', category: 'social', title: '오래된 친구 연락 망설임', diagnosis: '공백기 부담',
      symptom: '너무 오래돼서 이제 못 하겠음',
      prescription: '\'갑자기 생각나서\'로 시작하면 됩니다. 그 한 줄이면 충분해요',
      sideEffect: '답이 바로 안 올 수 있음',
      warning: '관계 복원을 보장하지는 않습니다',
      emoji: '🫂', color: '#ff8fb3', rarity: 'rare',
      shareText: '오래된 친구 연락 망설임 🫂💉', isPremium: false },
    { id: 'social-apology-delay', category: 'social', title: '사과 타이밍 놓침증', diagnosis: '지연에 따른 난이도 상승',
      symptom: '시간이 지날수록 더 꺼내기 어려움',
      prescription: '짧게 하세요. 긴 사과는 변명처럼 들립니다',
      sideEffect: '받아들여지는 데 시간이 걸릴 수 있음',
      warning: '상대의 반응은 예측할 수 없습니다',
      emoji: '🙇', color: '#ef6a5a', rarity: 'common',
      shareText: '사과 타이밍 놓침증 🙇💉', isPremium: false },
    { id: 'social-favor-refuse', category: 'social', title: '부탁 거절 불능증', diagnosis: '수락 자동화',
      symptom: '말이 끝나기 전에 이미 알겠다고 함',
      prescription: '\'생각해보고 알려줄게\'를 연습하세요. 즉답만 미뤄도 절반은 줄어듭니다',
      sideEffect: '미뤘다가 결국 하게 될 수 있음',
      warning: '인간관계의 손익은 계산해드릴 수 없습니다',
      emoji: '🙅', color: '#ffc66b', rarity: 'common',
      shareText: '부탁 거절 불능증 🙅💉', isPremium: false },
    { id: 'study-plan-perfect', category: 'study', title: '계획표만 예쁜 증후군', diagnosis: '준비 단계 고착',
      symptom: '계획 짜는 데 세 시간 씀',
      prescription: '계획은 접고 25분만 시작하세요. 진도가 계획을 고쳐줍니다',
      sideEffect: '계획표가 더러워지는 걸 견뎌야 함',
      warning: '새 다이어리 구매는 해결책이 아닙니다',
      emoji: '📋', color: '#8fd694', rarity: 'common',
      shareText: '계획표만 예쁜 증후군 📋💉', isPremium: false },
    { id: 'study-highlight-all', category: 'study', title: '형광펜 남용증', diagnosis: '중요도 판단 실패',
      symptom: '한 페이지가 전부 노란색',
      prescription: '한 쪽에 세 줄만 칠하세요. 다 중요하면 아무것도 안 중요해집니다',
      sideEffect: '다시 보면 왜 칠했는지 모를 수 있음',
      warning: '형광펜 소모량은 책임지지 않습니다',
      emoji: '🖍️', color: '#ffd166', rarity: 'common',
      shareText: '형광펜 남용증 🖍️💉', isPremium: false },
    { id: 'study-cafe-move', category: 'study', title: '카공 장소 순례증', diagnosis: '환경 탓 지속',
      symptom: '카페를 세 군데 옮기고 한 장 읽음',
      prescription: '오늘은 자리를 옮기지 마세요. 이동 시간이 공부 시간을 먹습니다',
      sideEffect: '집중이 안 되는 이유가 장소가 아니었음을 알게 됨',
      warning: '음료값은 환불되지 않습니다',
      emoji: '☕', color: '#b98a6f', rarity: 'common',
      shareText: '카공 장소 순례증 ☕💉', isPremium: false },
    { id: 'study-lecture-speed', category: 'study', title: '배속 강의 흘려듣기', diagnosis: '입력 속도 초과',
      symptom: '2배속으로 듣고 아무것도 안 남음',
      prescription: '1.25배로 낮추고 한 챕터만 제대로 들으세요',
      sideEffect: '진도가 느려 보일 수 있음',
      warning: '시험 결과를 보장하지 않습니다',
      emoji: '⏩', color: '#9aa8e0', rarity: 'common',
      shareText: '배속 강의 흘려듣기 ⏩💉', isPremium: false },
    { id: 'study-compare-progress', category: 'study', title: '남의 진도 염탐증', diagnosis: '비교로 인한 마비',
      symptom: '다들 나보다 앞서 있는 것 같음',
      prescription: '오늘 내 진도만 한 줄 적으세요. 어제의 나와만 비교하면 됩니다',
      sideEffect: '적어보면 생각보다 나쁘지 않음',
      warning: '타인의 진도는 확인해드릴 수 없습니다',
      emoji: '👀', color: '#b79aef', rarity: 'common',
      shareText: '남의 진도 염탐증 👀💉', isPremium: false },
    { id: 'study-restart-monday', category: 'study', title: '다음 주부터 증후군', diagnosis: '시작일 이월',
      symptom: '이번 주는 이미 망했다고 판단함',
      prescription: '오늘 15분만 하세요. 주 단위로 망하는 건 없습니다',
      sideEffect: '다음 주에도 같은 판단을 할 수 있음',
      warning: '지난주는 되돌릴 수 없습니다',
      emoji: '🔄', color: '#ffc66b', rarity: 'common',
      shareText: '다음 주부터 증후군 🔄💉', isPremium: false },
    { id: 'study-note-hoard', category: 'study', title: '자료 수집 중독', diagnosis: '다운로드만 반복',
      symptom: '저장은 많은데 연 적은 없음',
      prescription: '새로 받지 말고 이미 받은 것 하나만 여세요',
      sideEffect: '열어보면 이미 있던 걸 또 받았다는 걸 알게 됨',
      warning: '저장 용량은 책임지지 않습니다',
      emoji: '📂', color: '#8aa0c9', rarity: 'common',
      shareText: '자료 수집 중독 📂💉', isPremium: false },
    { id: 'fun-watchlist-freeze', category: 'fun', title: '볼 거 고르다 끝남', diagnosis: '선택 피로',
      symptom: '40분 고르고 결국 안 봄',
      prescription: '목록 맨 위 것을 10분만 트세요. 재미없으면 그때 바꾸면 됩니다',
      sideEffect: '10분 뒤에 또 고르게 될 수 있음',
      warning: '구독료는 환불되지 않습니다',
      emoji: '🎬', color: '#9aa8e0', rarity: 'common',
      shareText: '볼 거 고르다 끝남 🎬💉', isPremium: false },
    { id: 'fun-hobby-graveyard', category: 'fun', title: '취미 도구 방치증', diagnosis: '시작 후 이탈',
      symptom: '장비만 사고 세 번 쓰고 넣어둠',
      prescription: '꺼내서 눈에 보이는 데 두세요. 보이면 손이 갑니다',
      sideEffect: '안 쓰면 다시 넣게 됨',
      warning: '새 장비 구매는 처방에 없습니다',
      emoji: '🎸', color: '#b98a6f', rarity: 'common',
      shareText: '취미 도구 방치증 🎸💉', isPremium: false },
    { id: 'fun-game-one-more', category: 'fun', title: '한 판만 증후군', diagnosis: '종료 시점 상실',
      symptom: '한 판이 여섯 판이 됨',
      prescription: '지금 판이 끝나면 앱을 닫으세요. 다음 판은 내일도 있습니다',
      sideEffect: '닫고 나면 아쉬움이 남을 수 있음',
      warning: '랭킹 하락은 책임지지 않습니다',
      emoji: '🎮', color: '#b79aef', rarity: 'common',
      shareText: '한 판만 증후군 6판째 🎮💉', isPremium: false },
    { id: 'fun-concert-fomo', category: 'fun', title: '티켓팅 실패 후유증', diagnosis: '광클 좌절',
      symptom: '대기열 2만 번대를 봤음',
      prescription: '중계나 후기로 대신 보세요. 그것도 같이 즐긴 겁니다',
      sideEffect: '다음 공연 알림을 또 신청하게 됨',
      warning: '취소표는 예측할 수 없습니다',
      emoji: '🎟️', color: '#ff8fb3', rarity: 'rare',
      shareText: '티켓팅 실패 후유증 🎟️💉', isPremium: false },
    { id: 'fun-laugh-alone', category: 'fun', title: '혼자 빵 터짐증', diagnosis: '공유 대상 부재',
      symptom: '웃긴 걸 봤는데 보낼 사람이 애매함',
      prescription: '그냥 보내세요. 안 웃겨도 보낸 건 기억에 남습니다',
      sideEffect: '답이 \'?\'일 수 있음',
      warning: '유머 취향 차이는 조정되지 않습니다',
      emoji: '😂', color: '#ffd166', rarity: 'common',
      shareText: '혼자 빵 터짐증 😂💉', isPremium: false },
    { id: 'fun-playlist-stuck', category: 'fun', title: '같은 노래 무한 반복', diagnosis: '선곡 정체',
      symptom: '2주째 한 곡만 듣고 있음',
      prescription: '그 곡 아티스트의 다른 한 곡만 들어보세요',
      sideEffect: '새 곡이 또 무한 반복될 수 있음',
      warning: '취향 확장을 보장하지 않습니다',
      emoji: '🎧', color: '#5fb3a3', rarity: 'common',
      shareText: '같은 노래 무한 반복 2주차 🎧💉', isPremium: false },
    { id: 'fun-weekend-blank', category: 'fun', title: '주말 계획 공백증', diagnosis: '약속 없음 불안',
      symptom: '아무 일정 없는 게 불안함',
      prescription: '하나만 정하세요. 산책도 일정입니다',
      sideEffect: '정하고 나면 나가기 싫어질 수 있음',
      warning: '즐거움을 보장하지 않습니다',
      emoji: '📭', color: '#8fd694', rarity: 'common',
      shareText: '주말 계획 공백증 📭💉', isPremium: false },
  ];

  // ---------- 커스텀 진료실 원클릭 템플릿 (환자명/처방의는 템플릿과 무관하게 직접 입력) ----------
  const CUSTOM_TEMPLATES = [
    { label: '직장 상사 저격용', d: '눈치 없음 말기', rx: '눈치껏 좀 하세요 처방', w: '더 눈치 없어질 수 있음' },
    { label: '다이어트 팩폭용', d: '야식 참을성 결핍증', rx: '오늘 저녁은 그냥 굶는 셈 치기', w: '내일 더 배고파질 수 있음' },
    { label: '잠수쟁이 친구용', d: '답장 실종 증후군', rx: '읽었으면 답장 좀 하기', w: '읽씹 재발 가능성 높음' },
  ];

  window.MAUMJARO_RX_DATA = { RX_CATEGORIES, PRESCRIPTIONS_SEED, CUSTOM_TEMPLATES };
})();
